<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="especie">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="nombre">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="nombre-cientifico" type="xs:string" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="familia" type="xs:string"/>

                <xs:element name="distribucion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="zona" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>

            <xs:attribute name="estado" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="extinto"/>
                        <xs:enumeration value="amenazado"/>
                        <xs:enumeration value="sin-peligro"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

        </xs:complexType>
    </xs:element>

</xs:schema>