<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="netflix">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="serie" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>

                        <xs:attribute name="genero" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="suspense"/>
                                    <xs:enumeration value="ficcion"/>
                                    <xs:enumeration value="comedia"/>
                                    <xs:enumeration value="variado"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="temporadas" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="anio_inicio" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/>
                                    <xs:maxInclusive value="2026"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="estado" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="emision"/>
                                    <xs:enumeration value="finalizada"/>
                                    <xs:enumeration value="cancelada"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>